EnglishStudy_Web/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from EnglishStudy_Web import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'EnglishStudy_Web.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.IndexView.as_view(), name='home'),

    # /tracnghiem
    url(r'^tracnghiem/', include('tracnghiem.urls', namespace='tracnghiem')),

    # /accounts
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    # /about
    url(r'^about/', 'EnglishStudy_Web.views.about', name='about'),

    # /polls - example polls application
    url(r'^polls/', include('polls.urls', namespace='polls')),

    # /admin - Django built-in interactive Admin page
    url(r'^admin/', include(admin.site.urls)),
)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

accounts/urls.py
__author__ = 'k15bh_000'

from django.conf.urls import patterns, url, include

urlpatterns = patterns('',

                       # /accounts/auth/
                       url(r'^auth/', 'accounts.views.auth', name='auth'),

                       # /accounts/logout/
                       url(r'^logout/', 'accounts.views.logout_view', name='logout'),

                       # /accounts/detail/
                       url(r'^detail/', 'accounts.views.account_detail', name='detail'),

                       # /accounts/login/
                       url(r'^login', 'accounts.views.login_view', name='login'),

                       # /accounts/signup/
                       url(r'^signup', 'accounts.views.signup', name='signup'),

                       # /accounts/create_account
                       url(r'^create_account', 'accounts.views.create_account', name='create_account'),

)

polls/urls.py
from django.conf.urls import patterns, url,include

from polls import views

urlpatterns = patterns('',
    # /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /polls/<id>
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),

    # /polls/<id>/results/
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),

    # /polls/<id>/vote/
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),



)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractBaseUser
import datetime
from django.utils import timezone
from django.db.models.fields import IntegerField

# Create your models here.


class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, related_name='profile')

    # The additional attributes we wish to include.
    #website = models.URLField(blank=True)
    # picture = models.ImageField(upload_to='profile_images', blank=True)

    birthday = models.DateField(default=datetime.date(1994, 1, 1))
    home = models.CharField(default='Hanoi', max_length=200)
    score_of_the_last_test = IntegerField(default=0)
    total_score = IntegerField(default=0)
    REQUIRED_FIELDS = ['birthday', 'home', 'Score of the last tests', 'Total score']

    REQUIRED_FIELDS = ['Score of the last test', 'Total score']
    # Override the __str__() method to return out something meaningful!
    def __str__(self):
        return self.user.username

accounts/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from accounts.models import UserProfile
import datetime

# Create your views here.

# I want to return http referer for 2 levels, so I declared this global variable here
previous_request = None


# Check for a valid login - handle POST request
# Authentication system
def auth(request):
    username = request.POST['username']
    password = request.POST['password']

    # If user tick on "Ghi nhớ", request.POST['keepsession'] will be 'yes', else it will be 'no'
    if 'keepsession' in request.POST:
        keepsession = request.POST['keepsession']
    else:
        keepsession = 'no'

    print("User " + username + " authentication requested, keepsession=" + keepsession)

    user = authenticate(username=username, password=password)

    if user is not None:
        # Do not use like "keepsession is 'yes'" here. It will always return false
        # since 'is' is identity testing and '==' is for equality testing
        if keepsession == 'no':
            request.session.set_expiry(0)

        login(request, user)
        print("User " + username + " logged in")

        if previous_request is not None:
            return HttpResponseRedirect(previous_request.META.get('HTTP_REFERER'))
        else:
            return HttpResponseRedirect("../../")

    else:
        print("Authentication failed")
        return HttpResponse("<p>username or password is not correct<p>")


# This method use for handling POST request in signup_view

def create_new_user_object(username, email, password, birthday, home):
    user = User.objects.create_user(username=username, email=email, password=password)
    user.profile = UserProfile(birthday = birthday, home = home)
    user.save()
    user.profile.save()

def create_account(request):
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    password_verify = request.POST['password_verify']
    birthday = request.POST['birthday']
    home = request.POST['home']

    try:
        user = User.objects.get_by_natural_key(username=username)
    except User.DoesNotExist:
        user = None

    # Each condition in this list must be satisfied for the signing up process
    conditions = {
        'requested_username_is_available': user is None,
        'valid_email_address': "@" in email,
        'password_and_password_verify_is_matched': password == password_verify
    }

    if all(condition is True for condition in conditions.values()):
        create_new_user_object(username, email, password, birthday, home)
        return HttpResponse("<p>" + username + " registry successfully</p>")

    else:
        error_message = "Error. Please check your information<p>"
        if conditions['requested_username_is_available'] is False:
            error_message += "username is not available<br/>"

        if conditions['valid_email_address'] is False:
            error_message += "email address is invalid<br/>"

        if conditions['password_and_password_verify_is_matched'] is False:
            error_message += "password not matched<br/>"

        return HttpResponse(error_message + "</p>")


# users will manage their account here
def account_detail(request):
    return render(request, 'accounts/account_detail.html')


# call this function to sign user out
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


# user can login by using this view
def login_view(request):
    global previous_request
    previous_request = request
    return render(request, 'accounts/login.html')


# user can sign up by using this view
def signup(request):
    return render(request, 'accounts/signup.html')

accounts/templates/accounts/account_detail.html
{% if user.is_authenticated %}
    <p>Hi, {{ user.username }}</p>
    <p>{{ user.profile.total_score }}</p>
{% else %}
    <p>you haven't log in</p>
{% endif %}

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}

    <!-- General meta information -->
    <title>Login</title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta name="robots" content="index, follow"/>
    {#	<meta charset="utf-8" />#}
    <!-- // General meta information -->


    <!-- Load Javascript -->
    <script type="text/javascript" src="{% static "accounts/js/jquery.js" %}"></script>
    <script type="text/javascript" src="{% static "accounts/js/jquery.query-2.1.7.js" %}"></script>
    <script type="text/javascript" src="{% static "accounts/js/rainbows.js" %}"></script>
    <!-- // Load Javascipt -->

    <!-- Load stylesheets -->
    <link type="text/css" rel="stylesheet" href="{% static "accounts/css/style.css" %}" media="screen"/>
    <!-- // Load stylesheets -->

    <script>


        $(document).ready(function () {

            $("#submit1").hover(
                    function () {
                        $(this).animate({"opacity": "0"}, "slow");
                    },
                    function () {
                        $(this).animate({"opacity": "1"}, "slow");
                    });
        });


    </script>

</head>
<body>

<div id="wrapper">
    <div id="wrappertop"></div>

    <div id="wrappermiddle">

        <h2>Đăng nhập</h2>

        <form method="post" action="{% url 'accounts:auth' %}">{% csrf_token %}
            <div id="username_input">

                <div id="username_inputleft"></div>

                <div id="username_inputmiddle">
                    <input type="text" name="username" id="url" placeholder="Username">
                    <img id="url_user" src="{% static "accounts/images/mailicon.png" %}" alt="">
                </div>

                <div id="username_inputright"></div>

            </div>

            <div id="password_input">

                <div id="password_inputleft"></div>

                <div id="password_inputmiddle">
                    <input type="password" name="password" id="url" placeholder="Password">
                    <img id="url_password" src="{% static "accounts/images/passicon.png" %}" alt="">
                </div>

                <div id="password_inputright"></div>

            </div>

            <div id="submit">
                <input type="image" src="{% static "accounts/images/submit_hover.png" %}" id="submit1" value="Sign In">
                <input type="image" src="{% static "accounts/images/submit.png" %}" id="submit2" value="Sign In">
            </div>

            <div id="keepsession_checkbox"><input type="checkbox" name="keepsession" value="yes">Ghi nhớ</div>

            <div id="links_left">

                <a href="#">Quên mật khẩu?</a>

            </div>

            <div id="links_right"><a href="{% url "accounts:signup" %}">Đăng ký</a></div>
        </form>
    </div>

    <div id="wrapperbottom"></div>


</div>

</body>
</html>

accounts/templates/accounts/login_old.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
</head>
<body>
<div id="authentication">
    {% if user.is_authenticated %}
        Welcome {{ user.username }}<br/>
        <a href="{% url 'accounts:logout' %}">Logout</a>
    {% else %}
        <form ID="login" method="post" action="/accounts/auth/">{% csrf_token %}
            <table>
                <tr>
                    <td><input type="text" name="username" placeholder="username" size="15" maxlength="25"></td>
                    <td><input type="password" name="password" placeholder="password" size="15" maxlength="25"></td>
                    <td><input type="submit" name="dangnhap" value="Đăng Nhập"></td>
                </tr>
                <tr>
                    <td><input type="checkbox" name="keepsession" value="yes">Ghi nhớ</td>
                    <td><a href="accounts/forgot">Quên mật khẩu</a></td>
                    <td><a href="accounts/signup">Đăng ký</a></td>
                </tr>
            </table>
        </form>
    {% endif %}
</div>
</body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html>
<head>
    <title>Sign up</title>
</head>
<body>
<div id="authentication">
    <form ID="login" method="post" action="{% url 'accounts:create_account' %}">{% csrf_token %}
        <table>
            <tr>
                <td><input type="text" name="username" placeholder="Tên đăng nhập" size="15" maxlength="25"></td>
                <td><input type="password" name="password" placeholder="Mật khẩu" size="15" maxlength="25"></td>
                <td><input type="password" name="password_verify" placeholder="Mật khẩu kiểm tra" size="15" maxlength="25"></td>
            </tr>
            <tr>
                <td><input type="email" name="email" placeholder="E-mail" size="15" maxlength="40"></td>
                <td><input type="date" name="birthday" placeholder="Ngày sinh" size="15" maxlength="25"></td>
                <td><input type="text" name="home" size="15" placeholder="Địa chỉ" maxlength="25"></td>
            </tr>
            <tr><td><input type="submit" name="signup" value="Đăng ký"></td></tr>
        </table>
    </form>
</div>
</body>
</html>