EnglishStudy_Web/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from EnglishStudy_Web import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'EnglishStudy_Web.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.IndexView.as_view(), name='home'),

    # /tracnghiem
    url(r'^tracnghiem/', include('tracnghiem.urls', namespace='tracnghiem')),

    # /accounts
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    # /about
    url(r'^about/', 'EnglishStudy_Web.views.about', name='about'),

    # /polls - example polls application
    url(r'^polls/', include('polls.urls', namespace='polls')),

    # /admin - Django built-in interactive Admin page
    url(r'^admin/', include(admin.site.urls)),
)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

polls/urls.py
from django.conf.urls import patterns, url,include

from polls import views

urlpatterns = patterns('',
    # /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /polls/<id>
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),

    # /polls/<id>/results/
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),

    # /polls/<id>/vote/
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),



)

tracnghiem/urls.py
__author__ = 'k15bh_000'

from django.conf.urls import patterns, url

from tracnghiem import views

urlpatterns = patterns('',

    # /tracnghiem/
    url(r'^$', views.TracNghiemView.as_view(), name='index'),

    # /tracnghiem/post/
    url(r'^post', 'tracnghiem.views.post', name='post'),

    )

tracnghiem/models.py
from django.db import models
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=500)

    def __str__(self):              # __unicode__ on Python 2
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)
    # order = models.CharField(default=0,max_length=4)
    def __str__(self):              # __unicode__ on Python 2
        return self.choice_text

tracnghiem/views.py
from django.shortcuts import render
from django.views import generic
from tracnghiem.models import Question, Choice
from django.http import HttpResponse
# Create your views here.

class TracNghiemView(generic.ListView):
    template_name = 'tracnghiem/tracnghiem.html'
    context_object_name = 'list_of_questions'

    def get_queryset(self):
        return Question.objects.all()


def change_user_score(user, score):
    user.profile.score_of_the_last_test = score
    user.profile.total_score += score
    user.profile.save()


def post(request):
    #return HttpResponse("<p>You've just submitted<p>")

    QUESTION = 'question'
    score = 0
    count_questions = 1
    question = QUESTION + str(count_questions)

    while question in request.POST:
        if Choice.objects.get(id=request.POST[question]).is_correct is True:
            score = score + 1
        count_questions = count_questions + 1
        question = QUESTION + str(count_questions)

    change_user_score(request.user, score)
    return HttpResponse("<p> your score  at this test is "
                        + str(score) + " and your total... is "
                        +str(request.user.profile.total_score) + "</p>")



class ResultView(generic.DetailView):
    template_name = 'tracnghiem/result.html'

    def get_queryset(self):
        return None;

tracnghiem/templates/tracnghiem/result.html
<p>This page shows your results</p>

tracnghiem/templates/tracnghiem/tracnghiem.html
{% extends "base.html" %}

{% block head %}
    {% load staticfiles %}
    <link href="{% static 'tracnghiem/css/style.css' %}" rel="stylesheet">
{% endblock %}

{% block navbar_li %}
    <li><a href="/">Trang chủ</a></li>
    <li class="active"><a href="{% url 'tracnghiem:index' %}">Trắc nghiệm</a></li>
    <li><a href="/about">Liên hệ</a></li>
{% endblock %}


{% block content_container %}
    <div class="starter-template">
        {% if user.is_authenticated %}
            {% if list_of_questions %}
                <form method="post" action="{% url 'tracnghiem:post' %}">{% csrf_token %}
                    <ul>
                        {% for question in list_of_questions %}
                            <li>
                                {{ question.question_text }}
                                <ul>
                                    {% for choice in question.choice_set.all %}
                                        <label class="radio-inline">
                                            <input type="radio" name="question{{ question.id }}" id="{{ choice.id }}"
                                                   value="{{ choice.id }}">
                                            {{ choice.choice_text }}
                                        </label>
                                    {% endfor %}
                                </ul>
                            </li>
                        {% endfor %}
                    </ul>
                    <input type="submit" class="btn btn-success" name="submit" value="Lưu kết quả"/>
                </form>
            {% else %}
                <p>Không có gì thú vị ở đây cả</p>
            {% endif %}
        {% else %}
            <p>Bạn chưa đăng nhập</p>
        {% endif %}
    </div>
{% endblock %}