EnglishStudy_Web/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from EnglishStudy_Web import views

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'EnglishStudy_Web.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.IndexView.as_view(), name='home'),

    # /tracnghiem
    url(r'^tracnghiem/', include('tracnghiem.urls', namespace='tracnghiem')),

    # /accounts
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),

    # /about
    url(r'^about/', 'EnglishStudy_Web.views.about', name='about'),

    # /polls - example polls application
    url(r'^polls/', include('polls.urls', namespace='polls')),

    # /admin - Django built-in interactive Admin page
    url(r'^admin/', include(admin.site.urls)),
)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

accounts/urls.py
__author__ = 'k15bh_000'

from django.conf.urls import patterns, url, include

urlpatterns = patterns('',

                       # /accounts/auth/
                       url(r'^auth/', 'accounts.views.auth', name='auth'),

                       # /accounts/logout/
                       url(r'^logout/', 'accounts.views.logout_view', name='logout'),

                       # /accounts/detail/
                       url(r'^detail/', 'accounts.views.account_detail', name='detail'),

                       # /accounts/login/
                       url(r'^login', 'accounts.views.login_view', name='login'),

                       # /accounts/signup/
                       url(r'^signup', 'accounts.views.signup', name='signup'),

                       # /accounts/create_account
                       url(r'^create_account', 'accounts.views.create_account', name='create_account'),

)

polls/urls.py
from django.conf.urls import patterns, url,include

from polls import views

urlpatterns = patterns('',
    # /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /polls/<id>
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),

    # /polls/<id>/results/
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),

    # /polls/<id>/vote/
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),



)

EnglishStudy_Web/views.py
__author__ = 'k15bh_000'
from django.http import HttpResponse
from django.views import generic
from django.shortcuts import render

class IndexView(generic.ListView):
    template_name = 'index2.html'

    def get_queryset(self):
        return None

def about(request):
    return render(request, 'about.html')

EnglishStudy_Web/templates/README.html
đây là base.html
<h1 style="font: 20px">{% block id1 %}Block id1 here{% endblock %}</h1>
<p>{% block id2 %}Block id2 here{% endblock %}</p>


đây là page1.html
{% extends "base.html" %}
{% block id1 %}abcdef{% endblock %}
{% block id2 %}123456{% endblock %}


đây là page2.html
{% extends "base.html" %}
{% block id1 %}abcdef{% endblock %}



kết quả khi dịch template page1.html là:
<h1 style="font: 20px">abcdef</h1>
<p>123456</p>

kết quả khi dịch template page2.html là:
<h1 style="font: 20px">abcdef</h1>
<p>Block id2 here</p>

EnglishStudy_Web/templates/about.html
{% extends "base.html" %}

{% block navbar_li %}
    <li><a href="/">Trang chủ</a></li>
    <li><a href="{% url 'tracnghiem:index' %}">Trắc nghiệm</a></li>
    <li class="active"><a href="/about">Liên hệ</a></li>
{% endblock %}

{% block content_container %}
<h3>Title</h3>
    <p>Không có gì thú vị ở đây cả</p>
{% endblock %}

EnglishStudy_Web/templates/base.html
<!DOCTYPE HTML>
<html>


<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Bootstrap core JavaScript-->
    <!-- Place at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-2.1.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <link href="{% static 'css/base.css' %}" rel="stylesheet">

    {% block head %}{% endblock %}
</head>


<body>


<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">EnglishStudy Web</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                {% block navbar_li %}{% endblock %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }}<b
                                class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'accounts:detail' %}">Tài khoản</a></li>
                            <li><a href="{% url 'accounts:logout' %}">Thoát</a></li>
                            <li class="divider"></li>
                            <li class="dropdown-header">Nav header</li>
                            <li><a href="#">Separated link</a></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'accounts:login' %}">Đăng nhập</a></li>
                {% endif %}
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</div>


<div class="container">
    {% block content_container %}{% endblock %}
</div>

</body>


</html>

EnglishStudy_Web/templates/index2.html
{% extends "skeleton.html" %}
{% load staticfiles %}

{% block title %}English Study Web{% endblock %}

{% block content_of_website %}
    <div class="m-slider">
        <div class="slider-holder">
            <span class="slider-shadow"></span>
            <span class="slider-b"></span>

            <div class="slider flexslider">
                <ul class="slides">
                    <li>
                        <div class="img-holder">
                            <img src="{% static "images/img001.png" %}" alt=""/>
                        </div>

                    </li>
                    <li>
                        <div class="img-holder">
                            <img src="{% static "images/img1.png" %}" alt=""/>
                        </div>

                    </li>
                    <li>
                        <div class="img-holder">
                            <img src="{% static "images/img3.png" %}" alt=""/>
                        </div>

                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- end of slider -->
    <!-- main -->
    <div class="main">
        <a href="#" class="m-btn-grey grey-btn">request a demo</a>
        <section class="cols">
            <div class="col">
                <img src="{% static "images/tracnghiem.png" %}" alt=""/>

                <div class="col-cnt">
                    <h2>Bài Luyện Tiếng Anh</h2>

                    <p>Bài luyện Tiếng Anh giúp cho các bạn củng cố thêm kiến thức,<br/>rèn tuy duy, phản xạ Tiếng Anh
                    </p>
                    <a href="#" class="more">xem chi tiết</a>
                </div>
            </div>
            <div class="col">
                <img src="{% static "images/video.png" %}" alt=""/>

                <div class="col-cnt">
                    <h2>Bài Giảng</h2>

                    <p>English Study Web cung cấp cho các bạn đầy đủ những video bài giảng tiếng anh từ các giáo viên,
                        giảng viên có nhiều năm kinh nghiệm giảng dạy</p>
                    <a href="#" class="more">xem chi tiết</a>
                </div>
            </div>
            <div class="col">
                <img src="{% static "images/nghenhac.gif" %}" alt=""/>

                <div class="col-cnt">
                    <h2>Bài hát tiếng anh</h2>

                    <p>Bạn cảm thấy kĩ năng nghe của mình còn kém? Hãy luyện nghe tiếng anh qua các bài hát tiếng
                        anh</p>
                    <a href="#" class="more">xem chi tiết</a>
                </div>
            </div>
            <div class="cl">&nbsp;</div>
        </section>
        <section class="post">
            <div class="video-holder">
                <iframe width="435" height="243" src="//www.youtube.com/embed/hLQl3WQQoQ0" frameborder="0"
                        allowfullscreen></iframe>
            </div>

            <div class="post-cnt">
                <h2>Tại sao bạn nên học tiếng anh trực tuyến?</h2>

                <p>Bạn muốn nâng cao trình độ tiếng anh, nhưng lại không có thời gian lên lớp? <br/> Bạn muốn được học
                    Tiếng Anh mọi lúc, mọi nơi. English Study Web sẽ giúp bạn làm được điều mà các bạn mong muốn mà
                    không hề mất một khoản chi phí nào với: </p>

                <ul>
                    <li>Hệ thống bài giảng thông minh, phong phú, liên tục được cập nhật</li>
                    <li>Đội ngũ giáo viên trình độ cao sẽ liên tục hỗ trợ, đánh giá, chấm điểm bài học, sửa sai và giúp
                        bạn tiến bộ từng ngày.
                    </li>
                    <li>Ôn tập và học lại kiến thức theo trình độ của mình</li>
                    <li>Chia sẻ, học hỏi và thi đua với cộng đồng thành viên English Study Web</li>
                </ul>
            </div>
            <div class="cl">&nbsp;</div>
        </section>

        <section class="testimonial">

            <p><strong class="quote">“Trên trái đất làm gì có đường.<br/> Người ta đi mãi thì thành đường
                thôi.”</strong></p>

            <p class="author">Cố hương - Lỗ Tẫn</p>
        </section>
    </div>
{% endblock %}

EnglishStudy_Web/templates/skeleton.html
<!DOCTYPE html>
<html lang="en" style="-webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%;">
<head>
	{% load staticfiles %}
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=0" />
	<title>{% block title %}Your title here{% endblock %}</title>
	
	<link rel="stylesheet" href="{% static "css/style.css" %}" type="text/css" media="all" />
	<link rel="stylesheet" href="{% static "css/flexslider.css" %}" type="text/css" media="all" />
	<link href="http://fonts.googleapis.com/css?family=Ubuntu:400,500,700" rel='stylesheet' type='text/css' />
	
	<script src="{% static "js/jquery-2.1.0.min.js" %}" type="text/javascript"></script>
	<script src="{% static "js/jquery.flexslider-min.js" %}" type="text/javascript"></script>
	<script src="{% static "js/functions.js" %}" type="text/javascript"></script>
</head>
<body>
	<!-- wraper -->
	<div id="wrapper">
		<!-- shell -->
		<div class="shell">
			<!-- container -->
			<div class="container">
				<!-- header -->
				<header id="header">
					<h1 id="logo"><a href="/">Curve</a></h1>
					<!-- search -->
					<div class="search">
                    	
						<form method="post">
							<span class="field"><input type="text" class="field" value="keywords here ..." title="keywords here ..." /></span>
							<input type="submit" class="search-btn" value="" />
						</form>
                      
					</div>
					<!-- end of search -->
                    <!-- authentication -->
                    <div class="authentication">
								{% if user.is_authenticated %}
									<p>Xin chào <a href={% url 'accounts:detail' %}>{{ user.username }}</a> (<a href={% url 'accounts:logout' %}>Thoát</a>)</p>
								{% else %}
									<a href="{% url 'accounts:login' %}"><div class="buttom_login"><center><b>Đăng nhập</b></center></div></a>
								    <a href="{% url 'accounts:signup' %}"><div class="buttom_signup"><center><b>Đăng ký thành viên</b></center></div></a>
                                {% endif %}
                    </div>
                    <!-- end of authentication -->
				</header>
				<!-- end of header -->
				<!-- navigation -->
				<nav id="navigation">
					<a href="#" class="nav-btn">HOME<span class="arr"></span></a>
					<ul>
						<li class="active"><a href="/">Trang chủ</a></li>
						<li><a href="#">Giới thiệu</a></li>
						<li><a href="{% url 'tracnghiem:index' %}">Trắc nghiệm</a></li>
						<li><a href="#">Video</a></li>
						<li><a href="#">Bài hát tiếng anh</a></li>
						<li><a href="/about">Liên hệ</a></li>
					</ul>
				</nav>
				<!-- end of navigation -->
				<!-- slider -->
                {% block content_of_website %} content here {% endblock %}
				
				<!-- end of main -->
				<div class="socials">
					<div class="socials-inner">
						<h3>Follow us</h3>
						<ul>
							<li><a href="#" class="facebook-ico"><span></span>Facebook</a></li>
							<li><a href="#" class="twitter-ico"><span></span>Twitter</a></li>
							<li><a href="#" class="rss-feed-ico"><span></span>Rss-feed</a></li>
							<li><a href="#" class="myspace-ico"><span></span>myspace</a></li>
							
						</ul>
						<div class="cl">&nbsp;</div>
					</div>
				</div>
				
					<!-- end of footer-cols -->
					<div class="footer-bottom">
						<nav class="footer-nav">
							<ul>
								<li class="active"><a href="/">Trang chủ</a></li>
								<li><a href="#">Giới thiệu</a></li>
								<li><a href={% url 'tracnghiem:index' %}>Trắc nghiệm</a></li>
								<li><a href="#">Video</a></li>
								<li><a href="#">Bài hát tiếng anh</a></li>
								<li><a href="#">Liên hệ</a></li>
							</ul>
						</nav>
						<p class="copy">&copy; Copyright 2014 English Study Web <span>|</span> <strong>Design by Group 8, K57CA-UET-VNU,H</a></strong>
						<div class="cl">&nbsp;</div>
					</div>
				</div>
			</div>
			<!-- end of container -->	
		</div>
		<!-- end of shell -->	
	</div>
	<!-- end of wrapper -->
</body>
</html>